listen: 7000
backend: http://192.168.1.110:5000
content-security-policy:
  pattern: "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://*.vaptcha.net https://*.vaptcha.com https://*.gstatic.cn https://*.gstatic.com https://*.recaptcha.net; object-src 'none'; frame-ancestors 'self'; report-uri /report; report-to csp-endpoint"
  inline-script-src: 1
  inline-style-src:
  inline-type: nonce
report-to: >
  {
    "group_name": "csp-endpoint",
    "max_age": 86400,
    "endpoints": [
      {
        "url": "https://guanghe.co/report"
      }
    ],
    "include_subdomains": true
  }
report-uris: "/report"